name: NaturalHorses
version: ${project.version}-b${BUILD_NUMBER}
description: Allow horses to naturally spawn in old (non-1.6) chunks

author: add5tar
authors: [TfT_02]
website: http://dev.bukkit.org/server-mods/naturalhorses/

main: au.com.addstar.naturalhorses.NaturalHorses
softdepend: [Essentials, Vault, Multiverse-Core, My Worlds]
